### ISSUE TITLE
Linux version 4.13也能装上，不过不能创建wifi

### ISSUE THREAD

**Issue by fankcoder** [yandd/CF-WU810N_linux_driver#1]
用的ubuntu16.04，能装上，能搜到wifi也能连接别的，就是不能自己创建

Linux version 4.13.0-36-generic (buildd@lgw01-amd64-033) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)) #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018

还请大神赐教~

**Comment by yandd** [comment]
这个应该是不能自己创建热点吧，没测试过，我只是解决了一点编译问题的
